config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }
  #----------admin--------------
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get 'top' => 'items#top'
    get 'search' => 'items#search'
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :current_index
      end
    end
    resources :order_details, only: [:update]
  end
  #--------------------------------

  #----------customer--------------
  resource :customers, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :quit
    end
  end

  #----------caddresses--------------
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :customers, only: [:destroy, :quit] do
    member do
      patch :out
    end
  end
  #----------items--------------
  root to: "items#top"
  get 'about' => 'items#about'
  get 'search' => 'items#search', as: 'genre_search'
  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  #----------cart_items-----------------
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'

  get '/all_item' => 'cart_items#all_item'
  delete '/all_item' => 'cart_items#all_item'
  #--------------------------------

  #----------Orders-----------------
  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      get 'log'
      post 'completed'
      get 'thanks'
    end
  end
  #--------------------------------
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :shipping_cost, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true

  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  def self.total_amount_calculator(cart_items)
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.amount * cart_item.item.price
    end
    sum * 1.1
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update

    @order = Order.find(params[:id])
    status = Order.statuses[order_params[:status]]

    if @order.update(order_params)

      if status >= Order.statuses["入金確認"]
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      else
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 0)
        end
      end

      flash[:notice] = "注文ステータスを変更しました"
      redirect_to admin_order_path(@order)
    else
      @order_details = @order.order_details
      render "show"
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!# , unless: :admin_signed_in?

  def index
    @orders = current_customer.orders
  end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

  def log
    @cart_items = current_customer.cart_items
    if session[:order] == {}
      redirect_to new_order_path
    else
      @order = Order.new(session[:order])
    end
  end

  def new
    @customer = current_customer
    @order = Order.new
    @addresses = Address.where(customer: current_customer)
  end

  def create

    # session[:order].clear if session[:order] == nil

    pay_amount = Order.total_amount_calculator(current_customer.cart_items)
    shipping_cost = 800

    @order = Order.new(order_params)

    @order.customer_id = current_customer.id
    @order.total_payment = pay_amount + shipping_cost
    @order.shipping_cost = shipping_cost

    if params[:order][:address_selection] == "my_home"
      @order.address = current_customer.address
      @order.name = current_customer.last_name
      @order.postal_code = current_customer.postal_code
    end

    if params[:order][:address_selection] == "addresses"
      address = Address.find(params[:order][:address_id])
      @order.address = address.address
      @order.name = address.name
      @order.postal_code = address.postal_code
    end

    if params[:order][:address_selection] == "new_address"
      if [] == Address.where(customer_id: current_customer.id, address: @order.address, name: @order.name, postal_code: @order.postal_code)
        Address.create(customer_id: current_customer.id, address: @order.address, name: @order.name, postal_code: @order.postal_code)
      end
    end

    if @order.valid?
      session[:order] = @order
      redirect_to log_orders_path
    else
      @customer = current_customer
      @addresses = Address.where(customer: current_customer)
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def completed
    order = Order.create(order_params)
    current_customer.items.each do |cart_item|
      OrderDetail.create(item_id: cart_item.id, order_id: order.id, amount: cart_item.cart_items[0].amount, making_status: 0, price: cart_item.price)
    end

    CartItem.where(customer_id: current_customer.id).destroy_all
    session[:order].clear
    redirect_to thanks_orders_path(message: "thank_you_for_purchasing_it")
  end

  def thanks
    unless params[:message] == "thank_you_for_purchasing_it"
      redirect_to customers_path
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :customer_id,
      :address,
      :total_payment,
      :payment_method,
      :name,
      :postal_code,
      :shipping_cost,
      :status,
      :created_at,
      :updated_at
    )
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container mt-4">
  <div calss="row">
      <span class="px-3" style="font-size: 24px; background-color: #d3d3d3;">
			  注文履歴一覧
			</span>
      <table class="table table-hover table-bordered table-condensed mt-4">
        <thead class="bg-light">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td id="id-link">
              <%= link_to admin_order_path(order) , class: 'btn-link' do %>
                <%= order.created_at.strftime('%Y/%m/%d/%H:%M:%S')%>
              <% end %>
            </td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.order_details.count %></td>
            <td><%= order.status %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/log.html.erb
orderslog
<% provide(:title, "注文情報確認") %>
<h2 class="head-line title_h2 text-center">注文情報確認</h2>
<div calss="row">
  <div class="col-xs-9">
    <%# if current_customer.cart_items.present? %>
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td class="text-left">
                <%#= attachment_image_tag( cart.product, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%#= cart_item.count %>
              </td>
              <td class="text-right">
                ¥<%#= tax_price(cart_item.item.price).to_s(:delimited) %>
              </td>
              <td class="text-right">
                <%= current_customer.id %>
                  <%= cart_item.amount %>
              </td>
              <td class="text-right">
                ¥<%#= price(cart_item).to_s(:delimited) %>
              </td>
            </tr>
          <%# end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-3 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">¥<%#= @order.postage %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">¥<%#= total_price(@cart_items).to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">¥<%#= billing(@order).to_s(:delimited) %></td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payment_method %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= @order.postal_code %><%= @order.address %><%= @order.name %>
          </td>
        </tr>
      </table>

      <!-- 表示とformを分けて記入 -->
      <div class ="col-xs-11">
      <%#= form_with model: @order, url: customers_orders_path, method: :post, local: true do |f| %>
        <%#= link_to "注文情報入力へ戻る" , "", class: "btn btn-info col-xs-3 back" %>
        　　<i class="fas fa-shipping-fast fa-2x"></i>
        <%#= f.submit "購入を確定する", class: "btn btn-warning center-block col-xs-5" %>
      <%# end %>
      </div>
    <%# else %>
        <!-- if カートアイテムがない時 -->
        <p>お客様のショッピングカートに商品はありませんので注文確定ができません。</p>
        <p><%= link_to "商品一覧", items_path %>から商品をお探し下さい。</p>
    <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
	<h4 class="text-center m-3">注文履歴詳細</h4>
	<strong>注文情報</strong>
	  <table class="table table-bordered mt-2">
      <tr>
        <th class="bg-light">購入者</th>
        <td><%= @order.name %></td>
      </tr>
        <th class="bg-light">購入日</th>
  	    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      <tr>
      　<th class="bg-light">配送先</th>
        <td>
        	<%= @order.postal_code %><br>
        	<%= @order.address %><br>
        	<%= @order.name %>
        </td>
      </tr>
      <tr>
      　<th class="bg-light">支払方法</th>
        <% if @order.payment_method == 0 %>
        <td>クレジットカード</td>
        <% else %>
        <td>銀行振込</td>
        <% end %>
      </tr>
      <tr>
     		<th class="col-xs-4 bg-light">注文ステータス</th>
  	  	<td class="col-xs-6">
      		<%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %> <!--admin/orders#update-->
        		<%= f.select :status, Order.statuses.keys.to_a,{}, class: "order_status" %>
						<%= f.submit '更新' ,id: 'order-status' ,class: "btn-sm btn-success" %>
      		<% end %>
      	</td>
	    </tr>
		</table>

  	<div class="row">
  		<div class="col-md-8">
				<table class="table table-hover table-bordered table-inverse">
			    <thead>
		        <tr class="info">
		          <th class="col-xs-4">商品名</th>
		          <th>単価（税込）</th>
		          <th>数量</th>
		          <th>小計</th>
		          <th>製作ステータス</th>
		        </tr>
			    </thead>
					<tbody>
						<% @order_details.each do |order_detail| %>
							<tr>
		            <td class="text-left">
		              <%= order_detail.item.name %>
		            </td>
		            <td class="text-right">
		              ¥<%= tax_price(order_detail.item.price).to_s(:delimited) %>
		            </td>
		            <td class="text-right">
		              <%= order_detail.amount %>
		            </td>
		            <td class="text-right">
		              ¥<%= sub_price(order_detail).to_s(:delimited) %>
		            </td>
			          <td>
		            	<%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %><!--admin/order_details#update-->
			            	<%= f.select :making_status, OrderDetail.making_statuses.keys, class: "order_detail" %>
			            	<%= f.submit '更新',id: 'create-status', class: "btn btn-success" %>
		            	<% end %>
			          </td>
			      	</tr>
						<% end %>
					</tbody>
				</table>
  		</div>

		  <div class="col-md-3 mt-3">
				<table class="table table-hover table-bordered table-condensed">
					<tr>
	          <th class="info">商品合計</th>
						<td>¥<%= total_payment(@order_details) %></td>
					</tr>
					<tr>
						<th class="info">送料</th>
						<td>¥<%= @order.shipping_cost %></td>
					</tr>
					<tr>
						<th class="info">請求金額合計</th>
						<td>¥<%= total_payment(@order_details) + @order.shipping_cost.to_i %></td>
					</tr>
			  </table>
	  </div>
    <div class="col-xs-12">

    </div>
	</div>
 </div>