config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }
  #----------admin--------------
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get 'top' => 'items#top'
    get 'search' => 'items#search'
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :current_index
      end
    end
    resources :order_details, only: [:update]
  end
  #--------------------------------

  #----------customer--------------
  resource :customers, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :quit
    end
  end

  #----------caddresses--------------
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :customers, only: [:destroy, :quit] do
    member do
      patch :out
    end
  end
  #----------items--------------
  root to: "items#top"
  get 'about' => 'items#about'
  get 'search' => 'items#search', as: 'genre_search'
  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  #----------cart_items-----------------
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'

  get '/all_item' => 'cart_items#all_item'
  delete '/all_item' => 'cart_items#all_item'
  #--------------------------------

  #----------Orders-----------------
  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      get 'log'
      post 'completed'
      get 'thanks'
    end
  end
  #--------------------------------
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items, through: :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def update_without_current_password(params, *options)
    if params[:password].blank? || params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def quit
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "会員情報を変更しました"
      redirect_to admin_customer_path
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    # customer_path(resource) # 2021/03/21日に↓の記述に書き直しました。
    '/customers'
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_inactive_custmer, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_custmer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted
        redirect_to new_customer_session_path, alert: "退会済のユーザーです"
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!# , unless: :admin_signed_in?
  
  def show
    @customer = current_customer
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会しました またのご利用お待ちしております"
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/quit.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h4 class="text-center m-4 col-3 bg-light mx-auto">退会フォーム</h4>
      <div class="w-50 mx-auto">
        <p class="text-center mb-4">退会すると、会員登録情報や<br>
        これまでの購入履歴が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。</p>
      <div class="d-flex justify-content-center">
      <div>
        <%= link_to "退会しない", customers_path, class: "btn btn-primary mr-3" %>
      </div>
      <div>
        <%= link_to "退会する", out_customer_path(@customer), method: :patch, class: "btn btn-danger ml-3" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h4 class="m-4 col-2 bg-light text-center">マイページ</h4>
			<div class ="d-flex">
				<h4><strong class="information-link"><i class="far fa-user"></i>登録情報</strong></h4>
				<%= link_to "編集する", edit_customer_registration_path, class: "btn btn-success ml-3 mb-3" %>
			</div>
			<table class="table table-bordered table-condensed" >
				<tbody>
					<tr>
						<th class="info col-xs-2 bg-light">氏名</th>
						<td class="text-left"><%= @customer.last_name %>&ensp;<%= @customer.first_name %></td>
					</tr>
					<tr>
						<th class="bg-light">フリガナ</th>
						<td class="text-left"><%= @customer.last_name_kana %>&ensp;<%= @customer.first_name_kana %></td>
					</tr>
					<tr>
						<th class="bg-light">メールアドレス</th>
						<td class="text-left"><%= @customer.email %></td>
					</tr>
					<tr>
						<th class="bg-light">郵便番号</th>
						<td class="text-left"><%= @customer.postal_code %></td>
					</tr>
					<tr>
						<th class="bg-light">住所</th>
						<td class="text-left"><%= @customer.address %></td>
					</tr>
					<tr>
						<th class="bg-light">電話番号</th>
						<td class="text-left"><%= @customer.telephone_number %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-5">
			<table class="table table-borderless">
				<tr>
					<th><h5><strong>配送先</strong></h5></th>
					<td><%= link_to "一覧を見る", addresses_path, data: {"turbolinks" => false}, class: "shipping-btn mr-2 btn btn-primary form-control" %></td>
				</tr>
				<tr>
					<th><h5><strong>注文履歴</strong></h5></th>
					<td><%= link_to "一覧を見る", orders_path, id: 'order-index', class: "order-btn mr-2 btn btn-primary form-control" %></td>
				</tr>
      </table>
		</div>
	</div>
</div>