config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }
  #----------admin--------------
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get 'top' => 'items#top'
    get 'search' => 'items#search'
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :current_index
      end
    end
    resources :order_details, only: [:update]
  end
  #--------------------------------

  #----------customer--------------
  resource :customers, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :quit
    end
  end

  #----------caddresses--------------
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :customers, only: [:destroy, :quit] do
    member do
      patch :out
    end
  end
  #----------items--------------
  root to: "items#top"
  get 'about' => 'items#about'
  get 'search' => 'items#search', as: 'genre_search'
  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  #----------cart_items-----------------
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'

  get '/all_item' => 'cart_items#all_item'
  delete '/all_item' => 'cart_items#all_item'
  #--------------------------------

  #----------Orders-----------------
  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      get 'log'
      post 'completed'
      get 'thanks'
    end
  end
  #--------------------------------
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :customers, through: :cart_items
  has_many :cart_items
  has_many :order_details
  has_many :orders, through: :order_details

  validates :genre_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 300 }
  validates :price, presence: true

  attachment :image

  #------enumで数値指定-------
  # enum is_active: { 販売中: true, 販売停止中: false }
  #---------------------------

  def self.get_genre_list # カテゴリー一覧を所得するメソッド
    genre_str = Genre.all.pluck(:name)
    cate_hash = genre_str.zip(1..genre_str.size)
  end

  def self.admin?(customer) # とりあえず、アドミンかどうか確認出来るメソッドを仮設
    "Admin" == customer.class.name # <#%= Item.admin?(current_user) %>
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all.page(params[:page]).per(8)
  end

  def search
    @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(8)
    render "admin/items/index"
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :is_active, :genre_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_customer!, except: [:show, :index, :top, :about]# , unless: :admin_signed_in?

  def top
    @items = Item.where(is_active: true).page(params[:page]).per(4)
  end

  def index
    @items = Item.where(is_active: true).page(params[:page]).per(8)
  end

  def search
    @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(8)
    render "index"
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def log
  end

  def thanks
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :is_active, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/items/about.html.erb
<link href='/'>
  <div class="container">
	 <div class="row" >
		<div class="about-text col text-center">
      <h1>About</h1>
         ながのCAKEは全国発送可能なケーキ屋さんです。<br>
         お子様からお年寄りの方までお召し上がりいただけるよう<br>
         様々なバリエーションをご用意しております。<br>
         全国へ発送可のですので「いつ」でも「どこ」でもご注文いただけます<br>
         ぜひご注文ください。<br>
		  <div class="about" >
      </div>
	   </div>
	 </div>
  </div>
        
        

app/views/items/index.html.erb
	<div class="col bg-light d-flex justify-content-end">
		<%= form_tag(genre_search_path , method: :get) do %>
		<ul class="nav">
			<li><%= select(@search_content, :genre_id, Item.get_genre_list,{}, {class:"form-control p-1 mt-1"})%></li>
	 		<li><%= submit_tag "絞り込む", class:"p-1 m-1 btn btn-info" %></li>
	 		<li><%= link_to "一覧に戻る", items_path, class: 'to_index_link p-1 mt-1 btn btn-outline-secondary' %></li>
		</ul>
		<% end %>
	</div>
	<div class='col-md-8 mx-auto my-5'>
		<!--paramsのアクションがどこから来ているものなのかで分岐-->
		<% if params[:action] == "index" %>
		<h4 class="bg-light col-3 text-center">商品一覧</h4>
		<% else %>
		<%# binding.pry %>
		<h4 class="bg-light col-3 text-center"><%= @items[0].genre.name %>一覧</h4>
		<% end %>
			(全<%=@items.total_count %>件中、<%= @items.count %>件を表示)
		<div class="row">
			<% @items.each do |item| %>
				<div class='col-md-3 col-sm-6 mt-3'>
					<%= link_to item_path(item), class: 'img_link' do %>
						<%= attachment_image_tag(item, :image, fallback: "no-image-icon.jpg", class: "item_image", style: "width: 100%; height: 70%") %>
						<% end %>
					<div><%= item.name %></div>
					<div>¥<%= tax_price(item.price).to_s(:delimited) %></div>
		  	</div>
			<% end %>
		</div>
		<div class="mt-3">
			<%= paginate @items %>
		</div>

	</div>

app/views/items/show.html.erb
<div class="row mt-5">
  <div class='col-md-3 offset-md-3'>
    <%= attachment_image_tag(@item, :image, fallback: "no-image-icon.jpg", class: "item_image", style: "width: 100%; height: 80%") %>
  </div>
  <div class='col-md-4'>
    <p class="mt-3" style="font-size: 24px; font-weight: bold;"><%= @item.name %></p>
    <p style="font-size: 24px; margin-bottom: 50px;"><%= @item.introduction %></p>
    <spap style="font-size: 24px; font-weight: bold;">￥<%= tax_price(@item.price) %></span>
    <spap style="font-size: 18px; ">(税込)</span>
      <% if @item.is_active == true %>
        <p class="text-success mb-5 mb-1">販売中</p>
      <% else %>
        <p class="text-danger mb-5 mb-1">売切</p>
      <% end %>
      <% if customer_signed_in? %>

        <%= form_with url: cart_items_path, method: :post, local:true do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
        <div class="row">
          <%= f.select :amount, options_for_select((1..10).to_a.unshift(["個数選択", 1])), {}, {class: 'form-control col-3'}  %>
          <%= f.submit "カートに入れる", class: "btn btn-success ml-3" %>
        </div>
        <% end %>
      <% end %>
  </div>

app/views/items/top.html.erb
<div class="container">
  <div class="top mb-5" >
    <div class="top-text">
      <h1>Welcome to NaganoCake</h1>
      <p>
		    このサイトは、ケーキ販売のECサイトになります<br>
		    会員でない方も商品の閲覧はできますが<br>
		    購入には会員登録が必要になります<br>
      </p>
	  </div>
  </div>
  <h4 class="m-3">新着商品</h4>
  <div class="row mt-3">
    <% @items.each do |item| %>
    	<div class="col-3">
	      <%= link_to item_path(item), class: 'item_image' do %>
		      <div><%= attachment_image_tag(item, :image, size: "180x130",id: 'no_image', fallback: "no-image-icon.jpg", :alt => "image") %></div>
        <% end %>
        <div><%= item.name %></div>
	      <div><%= item.introduction %></div>
	      <div>¥ <%= tax_price(item.price) %></div>
    	</div>
    <% end %>
    <div class="col text-right m-5">
      <%= link_to "全ての商品を見る >", items_path, class: "btn-link  pull-right text-dark" %>
    </div>
  </div>
</div>