config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
  }
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
  }
  #----------admin--------------
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get 'top' => 'items#top'
    get 'search' => 'items#search'
    resources :genres, only: [:index, :create, :edit, :update, :show, :destroy]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :current_index
      end
    end
    resources :order_details, only: [:update]
  end
  #--------------------------------

  #----------customer--------------
  resource :customers, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :quit
    end
  end

  #----------caddresses--------------
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :customers, only: [:destroy, :quit] do
    member do
      patch :out
    end
  end
  #----------items--------------
  root to: "items#top"
  get 'about' => 'items#about'
  get 'search' => 'items#search', as: 'genre_search'
  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  #----------cart_items-----------------
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'

  get '/all_item' => 'cart_items#all_item'
  delete '/all_item' => 'cart_items#all_item'
  #--------------------------------

  #----------Orders-----------------
  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      get 'log'
      post 'completed'
      get 'thanks'
    end
  end
  #--------------------------------
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true

  def order_address
    postal_code + address + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items, through: :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def update_without_current_password(params, *options)
    if params[:password].blank? || params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :customers, through: :cart_items
  has_many :cart_items
  has_many :order_details
  has_many :orders, through: :order_details

  validates :genre_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 300 }
  validates :price, presence: true

  attachment :image

  #------enumで数値指定-------
  # enum is_active: { 販売中: true, 販売停止中: false }
  #---------------------------

  def self.get_genre_list # カテゴリー一覧を所得するメソッド
    genre_str = Genre.all.pluck(:name)
    cate_hash = genre_str.zip(1..genre_str.size)
  end

  def self.admin?(customer) # とりあえず、アドミンかどうか確認出来るメソッドを仮設
    "Admin" == customer.class.name # <#%= Item.admin?(current_user) %>
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :shipping_cost, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true

  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  def self.total_amount_calculator(cart_items)
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.amount * cart_item.item.price
    end
    sum * 1.1
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :making_status, presence: true
  validates :amount, presence: true
  validates :price, presence: true

  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/models/orderdproduct.rb
class Orderdproduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_cart
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  # 小数点切り捨てはfloor,３桁区切りはto_s(:delimited)
  # 税込の計算
  def tax_price(price)
    (price * 1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  # 合計金額の計算
  def total_payment(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    price
  end

  # 請求額の計算
  def billing(order)
    total_payment(current_cart) + order.shipping_cost.to_i
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/custmers_helper.rb
module CustmersHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <%#= content_tag(:div, value, class: key) %>
    <div class="<%= key %> w-75 mx-auto">
      <%= value %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <p class="footer-text">© 2021 - ROOKIES</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffdab9">
    <div class="container">
      <h3><%= link_to "NaganoCAKE", root_path, class: "text-body font-italicn text-decoration-none logo-text" %></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if customer_signed_in?  %>
          <div class="nav-item mt-2 ml-5">
                ようこそ、<strong><%= current_customer.last_name %><%= current_customer.first_name %></strong>さん！
          </div>
        <% end  %>
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item"><%= link_to "マイページ", customers_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "カート", cart_items_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link"  %></li>
          <% elsif current_admin %>
            <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link"  %></li>
          <% else %>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "管理者ログイン", new_admin_session_path, class: "nav-link"  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f62b1747c1.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="footer-fixed">
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/users/quit.html.erb
<div class="container">
  <h1>退会フォーム</h1>
  <div>
    <p>退会する場合は「退会する」を押してください</p>
  </div>
  <div class="d-flex">
    <div>
      <%= link_to "退会する", out_user_path(@user), method: :patch, class: "btn btn-danger" %>
    </div>
    <div>
      <%= link_to "退会しない", user_path(@user), class: "btn btn-primary" %>
    </div>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1 class="head-line text-center title_h2">マイページ</h1>
	<h3><strong class="information-link"><i class="far fa-user"></i>登録情報</strong></h3>

		<table class="table table-bordered table-condensed" >
			<tbody>
				<tr>
					<td class="info col-xs-2">氏名</td>
					<td class="text-left"><%= @user.last_name %><%= @user.first_name %></td>
				</tr>
				<tr>
					<td class="info">フリガナ</td>
					<td class="text-left"><%= @user.ruby_last_name %><%= @user.ruby_first_name %></td>
				</tr>
				<tr>
					<td class="info">メールアドレス</td>
					<td class="text-left"><%= @user.email %></td>
				</tr>
				<tr>
					<td class="info">郵便番号</td>
					<td class="text-left"><%= @user.postcode %></td>
				</tr>
				<tr>
					<td class="info">住所</td>
					<td class="text-left"><%= @user.address %></td>
				</tr>
				<tr>
					<td class="info">電話番号</td>
					<td class="text-left"><%= @user.phone_number %></td>
				</tr>
			</tbody>
		</table>

		<div class="d-flex">
		  <div>
				<%= link_to "配送先一覧を見る", shipping_addresses_path, data: {"turbolinks" => false}, class: "mr-2 btn btn-info" %>
			</div>
			<div>
				<%= link_to "注文履歴一覧を見る", orders_path, class: "mr-2 btn btn-info" %>
			</div>
			<div>
			  <%= link_to " ユーザー情報を編集する", edit_user_registration_path, class: "btn btn-success" %>
			</div>
		</div>
</div>